container:
  image: cirrusci/flutter:2.0.5

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test --reporter json | grep '^{.*}$' > report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter
