container:
  image: cirrusci/flutter:2.0.5

analysis_task:
  pub_cache:
    folder: ~/.pub-cache
  analysis_script: |
    flutter pub get
    flutter analyze

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: |
    flutter pub get
    flutter test --reporter json > report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter
